config/routes.rb
Rails.application.routes.draw do
  resources :gardens do
    resources :plants, only: %i[new create]
  end

  resources :plants, only: [:destroy] do
    resources :taggings, only: %i[new create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/garden.rb
class Garden < ApplicationRecord
  validates :name, presence: true
  validates :banner_url, presence: true

  has_many :plants, dependent: :destroy
end

app/models/plant.rb
class Plant < ApplicationRecord
  belongs_to :garden

  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings
end

app/models/tag.rb
class Tag < ApplicationRecord
end

app/models/tagging.rb
class Tagging < ApplicationRecord
  belongs_to :tag
  belongs_to :plant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/gardens_controller.rb
class GardensController < ApplicationController
  before_action :set_garden, only: %i[show edit update destroy]

  # GET /gardens or /gardens.json
  def index
    @gardens = Garden.all
  end

  # GET /gardens/1 or /gardens/1.json
  def show
    @plants = @garden.plants
  end

  # GET /gardens/new
  def new
    @garden = Garden.new
  end

  # GET /gardens/1/edit
  def edit; end

  # POST /gardens or /gardens.json
  def create
    @garden = Garden.new(garden_params)

    respond_to do |format|
      if @garden.save
        format.html { redirect_to garden_url(@garden), notice: 'Garden was successfully created.' }
        format.json { render :show, status: :created, location: @garden }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /gardens/1 or /gardens/1.json
  def update
    respond_to do |format|
      if @garden.update(garden_params)
        format.html { redirect_to garden_url(@garden), notice: 'Garden was successfully updated.' }
        format.json { render :show, status: :ok, location: @garden }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @garden.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gardens/1 or /gardens/1.json
  def destroy
    @garden.destroy

    respond_to do |format|
      format.html { redirect_to gardens_url, notice: 'Garden was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_garden
    @garden = Garden.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def garden_params
    params.require(:garden).permit(:name, :banner_url)
  end
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  def new
    @plant = Plant.new
    @garden = Garden.find(params[:garden_id])
  end

  def create
    # permit the parameters
    # make an instance of plant with the params
    @plant = Plant.new(plant_params)
    # assign which garden this plant belongs to
    # find the garden from the id in the URL
    @garden = Garden.find(params[:garden_id])
    @plant.garden = @garden
    # save
    @plant.save

    # redirect user to garden show
    redirect_to garden_path(@garden)
  end

  def destroy
    # find the plant to destroy
    @plant = Plant.find(params[:id])
    # destroy
    @plant.destroy

    # redirect the user back to garden
    redirect_to garden_path(@plant.garden)
  end

  private

  def plant_params
    params.require(:plant).permit(:name, :image_url)
  end
end

app/controllers/taggings_controller.rb
class TaggingsController < ApplicationController
  def new
    @tagging = Tagging.new
    @plant = Plant.find(params[:plant_id])
  end

  def create
    # { "tagging"=>{"tag_id"=>"2"}, "commit"=>"Create Tagging", "plant_id"=>"1"}
    # create Tagging instance based on the attribute in params[:tagging]
    @tagging = Tagging.new(tagging_params)
    # find the plant instance with the ID
    @plant = Plant.find(params[:plant_id])
    # assign the plant to that tagging
    @tagging.plant = @plant
    # save
    if @tagging.save
      # redirect the user to the garden show
      redirect_to garden_path(@plant.garden)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def tagging_params
    params.require(:tagging).permit(:tag_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gardens_helper.rb
module GardensHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/taggings_helper.rb
module TaggingsHelper
end

app/views/gardens/_form.html.erb
<%= simple_form_for(@garden) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :banner_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/gardens/_garden.html.erb
<div id="<%= dom_id garden %>">
  <p>
    <strong>Name:</strong>
    <%= garden.name %>
  </p>

  <p>
    <strong>Banner url:</strong>
    <%= garden.banner_url %>
  </p>

</div>

app/views/gardens/edit.html.erb
<h1>Editing garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Show this garden", @garden %> |
  <%= link_to "Back to gardens", gardens_path %>
</div>

app/views/gardens/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Gardens</h1>

<div id="gardens">
  <% @gardens.each do |garden| %>
    <%= render garden %>
    <p>
      <%= link_to "Show this garden", garden %>
    </p>
  <% end %>
</div>

<%= link_to "New garden", new_garden_path %>

app/views/gardens/new.html.erb
<h1>New garden</h1>

<%= render "form", garden: @garden %>

<br>

<div>
  <%= link_to "Back to gardens", gardens_path %>
</div>

app/views/gardens/show.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(<%= @garden.banner_url %>);">
  <div class="container">
    <h1><%= @garden.name %></h1>
    <div class="mt-2">
      <%= link_to "Edit this garden", edit_garden_path(@garden), class: "btn btn-primary" %>
      <%= link_to "Back to gardens", gardens_path, class: "btn btn-secondary" %>
      <%= link_to "Delete", garden_path(@garden), class: "btn btn-danger ", data: { turbo_method: :delete, turbo_confirm: "Sure??" } %>
    </div>
  </div>
</div>
<div class="container mt-4 d-flex flex-column gap-4">
  <% @plants.each do |plant| %>
    <div class="card-product">
      <img src="<%= plant.image_url %>" />
      <div class="card-product-infos d-flex flex-grow-1 justify-content-between align-items-center">
        <div>
          <h2><%= plant.name %></h2>
          <p>
            <% plant.tags.each do |tag| %>
              <span class="badge rounded-pill text-bg-primary"><%= tag.name %></span>
            <% end %>
          </p>
        </div>
        <div class="d-flex gap-2">
          <%= link_to "Tag", new_plant_tagging_path(plant), class: "btn btn-info" %>
          <%= link_to "Delete", plant_path(plant), class: "btn btn-danger text-white", data: { turbo_method: :delete }  %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GardensAndPlants1343</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/plants/new.html.erb
<h1>Plants#new</h1>
<%= simple_form_for [@garden, @plant] do |f| %>
  <%= f.input :name %>
  <%= f.input :image_url %>
  <%= f.submit %>
<% end %>

app/views/taggings/new.html.erb
<h1>Taggings#new</h1>
<%= simple_form_for [@plant, @tagging] do |f| %>
  <%= f.association :tag %>
  <%= f.submit %>
<% end %>